# NumPy Fundamentals: Locating Array Values
Please complete this assignment with your small group. Discussion is encouraged and a completed version is due before the next class.

In [1]:
import numpy as np

In [2]:
my_array = np.array([[12, 73, 68], [33, 25, 1], [54, 46, 92]])
my_array

array([[12, 73, 68],
       [33, 25,  1],
       [54, 46, 92]])

## Finding Minimum and Maximum Values


What if we want to find the smallest element in our array? NumPy's `min` function allows us to do just that:

In [3]:
print(f"The smallest element is: {np.min(my_array)}")

The smallest element is: 1


But *where* is the smallest element? NumPy also has a function to tell you its index:

In [4]:
print(f"The smallest element is at index: {np.argmin(my_array)}")

The smallest element is at index: 5


But our array is has 2 dimensions...what does index 5 mean for a 2D array?

Well if we flatten the array such that it's now 1D: 

In [5]:
my_flat_array = my_array.flatten()
print(f"Flat array: {my_flat_array}")

Flat array: [12 73 68 33 25  1 54 46 92]


Looks like the element at index 5 is indeed 1!

In [6]:
print(my_flat_array[5])

1


We can also use these functions to get the smallest element in each row or column:

In [7]:
# Note: 
# - compare elements in each row --> axis = 0 
# - compare elements in each column --> axis = 1

print(f"The smallest elements in each row: {np.min(my_array, axis = 0)}")
print(f"The smallest elements in each column: {np.min(my_array, axis = 1)}")

The smallest elements in each row: [12 25  1]
The smallest elements in each column: [12  1 46]


NumPy also has analgous functions for finding the maximum element:
- `np.max`: returns the largest element in the array
- `np.argmax`: returns the index of the largest element

### Q.1 Please find the largest value in `my_array`, the index of the largest value, and the largest values in each column

In [8]:
#print(f"The largest element in my_array is: { <YOUR ANSWER HERE> }")
#print(f"The largest element in my_array is at index: { n<YOUR ANSWER HERE> }")
#print(f"The largest elements in each column are: { <YOUR ANSWER HERE> }")

## Finding and Sorting Values Based On Conditions

In [9]:
new_array = np.array([[-18, 13, 83, 11], [28, 18, 12, -16]])
new_array

array([[-18,  13,  83,  11],
       [ 28,  18,  12, -16]])

NumPy also allows us to find values that meet a certain criteria using `np.where`

In [10]:
np.where(new_array > 20)

(array([0, 1]), array([2, 0]))

At first, these results do not seem to have a clear meaning. However, upon further inspection, we can see that the first list contains the row number and the second list contains the column index of each element that satisfies our condition

We can also get the indices where the condition is met directly:

In [11]:
np.argwhere(new_array > 20)

array([[0, 2],
       [1, 0]])

These are formatted much cleaner!

NumPy also has a specific function that tells us where all of the non-zero elements are in an array:

In [12]:
np.nonzero(new_array)

(array([0, 0, 0, 0, 1, 1, 1, 1]), array([0, 1, 2, 3, 0, 1, 2, 3]))

### Q.2 Use `np.where` to reproduce the output above

In [13]:
# print(np.where( <YOUR ANSWER HERE> ))

Lastly, `np.sort` provides us with sorting capabilities, but the default result may not be exactly what you expect.

In [14]:
np.sort(new_array)

array([[-18,  11,  13,  83],
       [-16,  12,  18,  28]])

### Q.3 What rules does NumPy seem to be following when sorting?

### A.3 YOUR ANSWER HERE

As an extension, trying seeing what values the axis parameter can take on and how that affects the sorting:

In [15]:
# Try printing these one at a time!
print(np.sort(new_array, axis=0))
print(np.sort(new_array, axis=1))

[[-18  13  12 -16]
 [ 28  18  83  11]]
[[-18  11  13  83]
 [-16  12  18  28]]


### Q.4 What impact does changing the `axis` argument have?

### A.4 YOUR ANSWER HERE

## Finding Values in a Database

Suppose we have a database of customers with attached IDs. 

If we want to look for a customer with a specific ID, we can use `np.argwhere` to find them. 

In [16]:
customers = np.array([['Dave','4101'],['Gwendolyn','3222'],['Anne','2315']])

### Q.5 Change the number 1234 in the `np.argwhere` function to Gwendolyn's ID number to get her index in the database

In [17]:
#gwen_id_index = <YOUR ANSWER HERE> 
#print(gwen_id_index)

Great! Now the variable `gwen_id_index` is an array with the index of Gwendolyn's user ID in the database. 

### Q.6 Index the variable `gwen_id_index` as necessary to extract the row and column indices as integers

In [18]:
#gwen_id_row = <YOUR ANSWER HERE> 
#gwen_id_col = <YOUR ANSWER HERE> 
#print(f"Gwen's ID is stored at index: { gwen_id_row },{ gwen_id_col }")

To search the database by name, we'll use `np.where`:

In [19]:
anne_name_index = np.argwhere(customers=='Anne')
print(anne_name_index)

[[2 0]]


### Q.7 Use and index the variable `anne_name_index` as necessary to access the entry `['Anne', '2315']` in `customers`

In [20]:
#anne_data = <YOUR ANSWER HERE> 
#print(f"Anne's database entry: { anne_data }")