# NumPy Fundamentals: Array Basics

Until now, we have focused on Python basics and built-in functions. In order to access specific packages, like NumPy, we need to import them like so:

In [2]:
# import the numpy as the shorthand np
import numpy as np

Using a standardized alias like `np` saves us a little bit of time later.

## NumPy Arrays
The most basic data structure in NumPy is an `ndarray`. 
The name `ndarray` comes from the fact that they can store "n dimensions" of data.

Lastly, arrays are similar to lists in that they can be indexed with the same syntax; however, unlike lists, NumPy arrays must contain numeric data types. 

Let's start by defining a simple 1D array, which can also be referred to as a vector:

In [3]:
# Create a vector from a list
my_list = [1,2,3,4]
my_vector = np.array(my_list)
print(type(my_list))
print(type(my_vector))

<class 'list'>
<class 'numpy.ndarray'>


Using what we learned from Module 1, we can index the list and the vector exactly the same way:

In [4]:
# Index the first elements:
print(f"The first element of the list: { my_list[0] }")
print(f"The first element of the vector: { my_vector[0] }")

The first element of the list: 1
The first element of the vector: 1


Using numpy arrays, we can make two dimensional arrays. This will look like a list *of* lists. The syntax for slicing should look familiar from indexing lists and tuples--brackets after an indexable variable indexes the variable.

In [10]:
my_2d_array = np.array([[5,6,7], [7,8,9]])
print(my_2d_array)
print(my_2d_array[1][1:3])


[[5 6 7]
 [7 8 9]]
[8 9]


We can also reassign variables as we would with lists:

In [11]:
my_2d_array[1][1] = 0
print(my_2d_array)

[[5 6 7]
 [7 0 9]]


Similarly, we can index and reassign indices in 3d arrays:

In [15]:
my_3d_array = np.array([[[9,10], [11,12]], [[13,14], [15,16]]])
print(my_3d_array)
print(my_3d_array[0][1][1])
my_3d_array[1][1][0] = 5
print(my_3d_array)

[[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
12
[[[ 9 10]
  [11 12]]

 [[13 14]
  [ 5 16]]]


## Doing Math With Arrays

### Peter -- Please show the following:
1. scalar multiplication of a simple vector
2. introduce basic vector/elementwise math by showing: 
    - `u * u = u**2`
    - `u * v` = ???
    - `v/u` = ???

In [7]:
u = np.array([1,2,3])
v = np.array([5,10,15])

## Common Array Constructors

### Peter -- Please demonstrate the functionality and use cases for the following `np.array` constructors:
- `np.zeros()`
- `np.ones()`
- `np.identity()` and explain what an identity matrix is 
- `np.nan()` and explain what `np.nan`/`NaN` is 
- `np.empty()` and highlight that the output is not exactly zero
- `np.full()`
- `np.tile()`

Lastly, please compare `np.linspace` vs. `arange` vs. `range()`

## Determining Matrix Size

It's very common to need the the number of elements in a list or array when programming. In Python, the words length, size, and shape all have different meanings!

The `len` function in Python is short for "length" and returns the number of items in a list. 

Let's see a quick example using our list from earlier: 

In [10]:
my_list_length = len(my_list)
print(f" The list \n {my_list} \n has {my_list_length} elements")

 The list 
 [1, 2, 3, 4] 
 has 4 elements


The `len` function works the same way for both lists and vectors like `my_vector`, which is represented by a 1D matrix.

The code below should return the same values for `my_list` and `my_vector` because they have the same number of elements:

In [11]:
list_length = len(my_list)
vector_length = len(my_vector)

print(my_list, type(my_list))
print(f"List length: {list_length}\n")

print(my_vector, type(my_vector))
print(f"Vector length: {vector_length}")

[1, 2, 3, 4] <class 'list'>
List length: 4

[1 2 3 4] <class 'numpy.ndarray'>
Vector length: 4


What happens if we use `len` on a nested list? In this case, the function does not care about the contents of the nested lists. It will treat the nested lists like any other data type. 

Here's an example of a list containing three nested lists:

In [12]:
my_nested_list = [[1, 2], [3, 4, 5], [6]]
print(f"Number of elements in nested list: {len(my_nested_list)}")

Number of elements in nested list: 3


Even though there are 6 integers in total contained in the nested list, the `len` function returns 3 because it only counts the nested lists within the list as elements. 

We can show this by printing the types of each element:

In [13]:
for element in my_nested_list:
    print(type(element))

<class 'list'>
<class 'list'>
<class 'list'>


If we want the length of an individual nested list, we can specify which nested list and print its length using the following code:

In [14]:
# Length of the first nested list
print(len(my_nested_list[0]))   

# Length of the second nested list
print(len(my_nested_list[1]))

# Length of the third nested list   
print(len(my_nested_list[2]))   

2
3
1


How will `len()` work with a 2D array?

In [18]:
new_2d_array = np.array([[7, 8, 9], [10, 11, 12]])

print(f"Nested list: \n{my_nested_list} \nlength: {len(my_nested_list)}\n")
print(f"2D array: \n{new_2d_array} \nlength: {len(new_2d_array)}")

Nested list: 
[[1, 2], [3, 4, 5], [6]] 
length: 3

2D array: 
[[ 7  8  9]
 [10 11 12]] 
length: 2


Looks like `len` returns the number of rows in our matrix!

Even though we see six total elements in each, `len(my_nested_list) != len(my_2d_array)` because of the differences in structure.

#### The `shape` and `size` properties
But what if we want the number of columns? Or the total number of elements in our matrix? 

With 2D arrays, we have a couple of properties that return similar information to `len`. We can use `size` to return the total number of elements and `shape` to return the total number of rows and columns (as a tuple).


In [68]:
# Get size and shape of 2D array
elements_in_array = my_2d_array.size
num_rows, num_cols = my_2d_array.shape
print(f" The array \n\n {my_2d_array} \n\n has {elements_in_array} elements ")
print(f" Its shape is: {my_2d_array.shape} ")
print(f" This means that there are {num_rows} rows and {num_cols} columns ")

 The array 

 [[1 2 3]
 [4 5 6]] 

 has 6 elements 
 Its shape is: (2, 3) 
 This means that there are 2 rows and 3 columns 


In [67]:
# Get size and shape of 3D array
elements_in_3d_array = my_3d_array.size
num_rows, num_cols, num_layers = my_3d_array.shape
print(f" The array \n\n {my_3d_array} \n\n has {elements_in_3d_array} elements ")
print(f" Its shape is: {my_3d_array.shape} ")
print(f" This means that there are {num_rows} rows, {num_cols} columns, and {num_layers} layers ")

 The array 

 [[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]] 

 has 8 elements 
 Its shape is: (2, 2, 2) 
 This means that there are 2 rows, 2 columns, and 2 layers 


To summarize:
- `len`: returns the number of elements in a list/1D array *or* the number of rows in the array if the number of dimensions >= 2
- `shape`: a tuple of numbers representing the size of each dimension
- `size`: the total number of elements